 export const astrologers = [
    {
      _id: "2",
      name: "Priyanka",
      rating: 5,
      profileImage: "https://cdn.anytimeastro.com/dashaspeaks/expert/thumb/628289f4-bd17-4d80-b2d6-b3586fcb824a.png",
      about: "Hey! I have been serving as a Tarot Reader and Intuitive Astrologer for more than a decade...",
      experience: "10+ Years",
      languages: ["English", "Hindi", "Sindhi"],
      specializations: [
        "Horary Astrology",
        "Break-Up & Divorce",
        "Career & Job",
        "Cheating & Affairs",
        "Marital Life",
        "Love & Relationship",
        "Kids & Education",
        "Vedic Astrology",
        "Finance & Business",
        "Tarot Reading",
      ],
      availability: [
        { day: "Saturday", date: "November 23", status: "Available" },
        { day: "Sunday", date: "November 24", status: "Not Available" },
        { day: "Monday", date: "November 25", status: "07:00 AM 08:00 AM" },
        { day: "Tuesday", date: "November 26", status: "Not Available" },
        { day: "Wednesday", date: "November 27", status: "Not Available" },
        { day: "Thursday", date: "November 28", status: "Not Available" },
        { day: "Friday", date: "November 29", status: "Not Available" },
      ],
      reviewData: {
        total: 3611,
        items: [
          { id: 1, initial: "L", name: "Lakshmi Kumari", rating: 5, comment: "bhot bhot bhot badhiya bhot he badhiya experience raha..." },
          { id: 2, initial: "N", name: "neha", rating: 5, comment: "She is very polite n helpful" },
          { id: 3, initial: "G", name: "Gloria SugandhitTopno", rating: 5, comment: "Priyanka p , maam is very excellent..." },
          { id: 4, initial: "R", name: "Rati Sharma Sharma", rating: 5, comment: "Mam is very supportive" },
          { id: 5, initial: "S", name: "Saloni", rating: 5, comment: "Very good experience" },
        ]
      },
      shareOptions: [
        { name: "Telegram", icon: "📨" },
        { name: "Pinterest", icon: "📌" },
        { name: "Facebook", icon: "📖" },
        { name: "X", icon: "🐦" },
        { name: "LinkedIn", icon: "🔗" },
        { name: "WhatsApp", icon: "📱" },
        { name: "Email", icon: "📧" },
        { name: "Copy Link", icon: "🔗" },
      ],
      gifts: [
        { id: 1, name: "Heart", price: 21, icon: "❤️" },
        { id: 2, name: "Flowers", price: 31, icon: "💐" },
        { id: 3, name: "Pooja Thali", price: 31, icon: "🙏" },
        { id: 4, name: "Clove", price: 51, icon: "🌺" },
        { id: 5, name: "Chocolate", price: 51, icon: "🍫" },
        { id: 6, name: "Crown", price: 101, icon: "👑" },
        { id: 7, name: "Magician", price: 101, icon: "🎭" },
        { id: 8, name: "Laddus", price: 501, icon: "🍯" },
        { id: 9, name: "Dakshina", price: 1100, icon: "🪙" },
        { id: 10, name: "Ganesha", price: 2100, icon: "🕉️" },
        { id: 11, name: "Shivling", price: 5100, icon: "🛕" },
      ],
      photoGallery: [
        { id: 1, type: "video", thumbnail: "https://cdn.anytimeastro.com/dashaspeaks/expert/thumb/628289f4-bd17-4d80-b2d6-b3586fcb824a.png" },
        { id: 2, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/1754691/thumb_43d23aa4-90d7-4279-92e0-ffe26db1ec11.png" },
        { id: 3, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/1754691/thumb_17303d50-4aa4-4e4c-88ac-75aadb51841b.png" },
        { id: 4, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/1754691/thumb_c4f67a1a-c6d0-4ca3-b30c-c2e0d13964ff.png" },
        { id: 5, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/1754691/thumb_c7b34d49-6a18-4110-9317-e78b5f8b0042.png" },
      ],
      callChargePerMinute: "₹299",
      chatChargePerMinute: "₹299"
    },
    {
      _id: "1",
      name: "Acharya Rajesh",
      rating: 4.9,
      profileImage: "https://cdn.anytimeastro.com/dashaspeaks/expert/thumb/acharya-profile.png",
      about: "With 15+ years of experience in Vedic astrology, I specialize in providing accurate predictions and guidance for life's important decisions...",
      experience: "15+ Years",
      languages: ["English", "Hindi", "Sanskrit", "Gujarati"],
      specializations: [
        "Vedic Astrology",
        "Career Guidance",
        "Marriage Compatibility",
        "Business Astrology",
        "Health Astrology",
        "Muhurat Timing",
        "Gem Recommendations",
        "Vaastu Shastra",
        "Numerology",
        "Past Life Reading",
      ],
      availability: [
        { day: "Saturday", date: "November 23", status: "Not Available" },
        { day: "Sunday", date: "November 24", status: "Available" },
        { day: "Monday", date: "November 25", status: "09:00 AM 10:00 AM" },
        { day: "Tuesday", date: "November 26", status: "Available" },
        { day: "Wednesday", date: "November 27", status: "Not Available" },
        { day: "Thursday", date: "November 28", status: "Available" },
        { day: "Friday", date: "November 29", status: "Not Available" },
      ],
      reviewData: {
        total: 2847,
        items: [
          { id: 1, initial: "R", name: "Rajesh Kumar", rating: 5, comment: "Very accurate predictions and helpful guidance..." },
          { id: 2, initial: "A", name: "Amit Shah", rating: 4, comment: "Good consultation, practical solutions provided" },
          { id: 3, initial: "P", name: "Priya Patel", rating: 5, comment: "Amazing experience, very knowledgeable..." },
          { id: 4, initial: "K", name: "Krishna Murthy", rating: 5, comment: "Excellent guidance for business decisions" },
          { id: 5, initial: "M", name: "Meera Desai", rating: 5, comment: "Very satisfied with the consultation" },
        ]
      },
      shareOptions: [
        { name: "Telegram", icon: "📨" },
        { name: "Pinterest", icon: "📌" },
        { name: "Facebook", icon: "📖" },
        { name: "X", icon: "🐦" },
        { name: "LinkedIn", icon: "🔗" },
        { name: "WhatsApp", icon: "📱" },
        { name: "Email", icon: "📧" },
        { name: "Copy Link", icon: "🔗" },
      ],
      gifts: [
        { id: 1, name: "Heart", price: 21, icon: "❤️" },
        { id: 2, name: "Flowers", price: 31, icon: "💐" },
        { id: 3, name: "Pooja Thali", price: 31, icon: "🙏" },
        { id: 4, name: "Clove", price: 51, icon: "🌺" },
        { id: 5, name: "Chocolate", price: 51, icon: "🍫" },
        { id: 6, name: "Crown", price: 101, icon: "👑" },
        { id: 7, name: "Magician", price: 101, icon: "🎭" },
        { id: 8, name: "Laddus", price: 501, icon: "🍯" },
        { id: 9, name: "Dakshina", price: 1100, icon: "🪙" },
        { id: 10, name: "Ganesha", price: 2100, icon: "🕉️" },
        { id: 11, name: "Shivling", price: 5100, icon: "🛕" },
      ],
      photoGallery: [
        { id: 1, type: "video", thumbnail: "https://cdn.anytimeastro.com/dashaspeaks/expert/thumb/acharya-video.png" },
        { id: 2, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/acharya1.png" },
        { id: 3, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/acharya2.png" },
        { id: 4, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/acharya3.png" },
        { id: 5, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/acharya4.png" },
      ],
      callChargePerMinute: "₹399",
      chatChargePerMinute: "₹349"
    },
    {
      _id: "3",
      name: "Guruji Ashish",
      rating: 4.7,
      profileImage: "https://cdn.anytimeastro.com/dashaspeaks/expert/thumb/ashish-profile.png",
      about: "Renowned Vedic astrologer with deep knowledge of Nadi Astrology and Palmistry. Providing guidance through ancient wisdom for modern problems...",
      experience: "18+ Years",
      languages: ["English", "Hindi", "Punjabi", "Urdu"],
      specializations: [
        "Nadi Astrology",
        "Palmistry",
        "Gemology",
        "Face Reading",
        "Marriage Matching",
        "Career Guidance",
        "Business Solutions",
        "Property Matters",
        "Foreign Travel",
        "Legal Matters",
      ],
      availability: [
        { day: "Saturday", date: "November 23", status: "Not Available" },
        { day: "Sunday", date: "November 24", status: "Available" },
        { day: "Monday", date: "November 25", status: "Available" },
        { day: "Tuesday", date: "November 26", status: "11:00 AM 12:00 PM" },
        { day: "Wednesday", date: "November 27", status: "Not Available" },
        { day: "Thursday", date: "November 28", status: "Available" },
        { day: "Friday", date: "November 29", status: "Available" },
      ],
      reviewData: {
        total: 4256,
        items: [
          { id: 1, initial: "H", name: "Harpreet Singh", rating: 5, comment: "Guruji's predictions are amazingly accurate..." },
          { id: 2, initial: "M", name: "Mohammed Khan", rating: 4, comment: "Very helpful guidance for business decisions" },
          { id: 3, initial: "J", name: "Jasmine Kaur", rating: 5, comment: "Best astrologer for marriage matching..." },
          { id: 4, initial: "A", name: "Arjun Malhotra", rating: 5, comment: "Excellent palm reading session" },
          { id: 5, initial: "K", name: "Kiran Sharma", rating: 4, comment: "Very knowledgeable and patient" },
        ]
      },
      shareOptions: [
        { name: "Telegram", icon: "📨" },
        { name: "Pinterest", icon: "📌" },
        { name: "Facebook", icon: "📖" },
        { name: "X", icon: "🐦" },
        { name: "LinkedIn", icon: "🔗" },
        { name: "WhatsApp", icon: "📱" },
        { name: "Email", icon: "📧" },
        { name: "Copy Link", icon: "🔗" },
      ],
      gifts: [
        { id: 1, name: "Heart", price: 21, icon: "❤️" },
        { id: 2, name: "Flowers", price: 31, icon: "💐" },
        { id: 3, name: "Pooja Thali", price: 31, icon: "🙏" },
        { id: 4, name: "Clove", price: 51, icon: "🌺" },
        { id: 5, name: "Chocolate", price: 51, icon: "🍫" },
        { id: 6, name: "Crown", price: 101, icon: "👑" },
        { id: 7, name: "Magician", price: 101, icon: "🎭" },
        { id: 8, name: "Laddus", price: 501, icon: "🍯" },
        { id: 9, name: "Dakshina", price: 1100, icon: "🪙" },
        { id: 10, name: "Ganesha", price: 2100, icon: "🕉️" },
        { id: 11, name: "Shivling", price: 5100, icon: "🛕" },
      ],
      photoGallery: [
        { id: 1, type: "video", thumbnail: "https://cdn.anytimeastro.com/dashaspeaks/expert/thumb/ashish-video.png" },
        { id: 2, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/ashish1.png" },
        { id: 3, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/ashish2.png" },
        { id: 4, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/ashish3.png" },
        { id: 5, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/ashish4.png" },
      ],
      callChargePerMinute: "₹499",
      chatChargePerMinute: "₹449"
    },
    {
      _id: "4",
      name: "Yogini Sunita",
      rating: 4.9,
      profileImage: "https://cdn.anytimeastro.com/dashaspeaks/expert/thumb/sunita-profile.png",
      about: "Specialist in Yogic Astrology combining traditional Vedic wisdom with yoga and meditation practices. Helping seekers find their spiritual path...",
      experience: "14+ Years",
      languages: ["English", "Hindi", "Tamil", "Telugu"],
      specializations: [
        "Yogic Astrology",
        "Meditation Guidance",
        "Spiritual Healing",
        "Chakra Balancing",
        "Past Life Reading",
        "Karma Analysis",
        "Life Purpose",
        "Relationship Healing",
        "Energy Reading",
        "Mantra Therapy",
      ],
      availability: [
        { day: "Saturday", date: "November 23", status: "Available" },
        { day: "Sunday", date: "November 24", status: "Not Available" },
        { day: "Monday", date: "November 25", status: "Available" },
        { day: "Tuesday", date: "November 26", status: "02:00 PM 03:00 PM" },
        { day: "Wednesday", date: "November 27", status: "Available" },
        { day: "Thursday", date: "November 28", status: "Not Available" },
        { day: "Friday", date: "November 29", status: "Available" },
      ],
      reviewData: {
        total: 3124,
        items: [
          { id: 1, initial: "S", name: "Shanti Reddy", rating: 5, comment: "Life-changing spiritual guidance..." },
          { id: 2, initial: "R", name: "Ramya Krishna", rating: 5, comment: "Amazing chakra healing session" },
          { id: 3, initial: "V", name: "Vishnu Prasad", rating: 5, comment: "Best meditation guidance ever..." },
          { id: 4, initial: "T", name: "Tara Menon", rating: 4, comment: "Very insightful past life reading" },
          { id: 5, initial: "P", name: "Pranav Kumar", rating: 5, comment: "Excellent karma analysis" },
        ]
      },
      shareOptions: [
        { name: "Telegram", icon: "📨" },
        { name: "Pinterest", icon: "📌" },
        { name: "Facebook", icon: "📖" },
        { name: "X", icon: "🐦" },
        { name: "LinkedIn", icon: "🔗" },
        { name: "WhatsApp", icon: "📱" },
        { name: "Email", icon: "📧" },
        { name: "Copy Link", icon: "🔗" },
      ],
      gifts: [
        { id: 1, name: "Heart", price: 21, icon: "❤️" },
        { id: 2, name: "Flowers", price: 31, icon: "💐" },
        { id: 3, name: "Pooja Thali", price: 31, icon: "🙏" },
        { id: 4, name: "Clove", price: 51, icon: "🌺" },
        { id: 5, name: "Chocolate", price: 51, icon: "🍫" },
        { id: 6, name: "Crown", price: 101, icon: "👑" },
        { id: 7, name: "Magician", price: 101, icon: "🎭" },
        { id: 8, name: "Laddus", price: 501, icon: "🍯" },
        { id: 9, name: "Dakshina", price: 1100, icon: "🪙" },
        { id: 10, name: "Ganesha", price: 2100, icon: "🕉️" },
        { id: 11, name: "Shivling", price: 5100, icon: "🛕" },
      ],
      photoGallery: [
        { id: 1, type: "video", thumbnail: "https://cdn.anytimeastro.com/dashaspeaks/expert/thumb/sunita-video.png" },
        { id: 2, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/sunita1.png" },
        { id: 3, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/sunita2.png" },
        { id: 4, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/sunita3.png" },
        { id: 5, type: "image", src: "https://cdn.anytimeastro.com/dashaspeaks/experts/gallary/live/sunita4.png" },
      ],
      callChargePerMinute: "₹399",
      chatChargePerMinute: "₹349"
    }
  ];


   